spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8001
          predicates:
            - Path=/auth/**
server:
  port: 8080

logging:
  config: classpath:logback-spring.xml